name: deploy-bicep-configuration

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
  workflow_dispatch:  

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: iac/bicep/completed/ampls-poc/bicep

env: 
    location: eastus2
    azCliversion: latest
    stackName: ampls-poc
    templateFile: main.bicep
    templateParametersFile: main.bicepparam
    operation: plan # options: plan, deploy, rollback
    environment: dev # options: dev, tst, prd

jobs:
  call-update-runner-tools:
    uses: ./reusable-update-runner-tools.yml
    with:
     name: update-runner-tools

  provision:
    runs-on: self-hosted # https://github.com/orgs/community/discussions/120813
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: login-with-umi-oidc
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}   

    - name: plan
      if: ${{ env.operation == 'plan' }}
      run: |
        az --version
        az account show
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az deployment sub create --location ${{ env.location }} --template-file ${{ env.templateFile }} --parameters ${{ env.templateParametersFile }} \
        --what-if --verbose

    - name: deploy
      if: ${{ env.operation == 'deploy' }}
      run: |
        az --version
        az account show
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az stack sub create --name ${{ env.stackName }} --location ${{ env.location }} --template-file ${{ env.templateFile }} --parameters ${{ env.templateParametersFile }} \
        --deny-settings-mode none --action-on-unmanage deleteAll --yes --verbose
    
    - name: rollback
      if: ${{ env.operation == 'rollback' }}
      run: |
        az --version
        az account show
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az stack sub delete --name ${{ env.stackName }} --action-on-unmanage deleteAll --yes --verbose

    



